import { generateIdentifier, logger } from '@next/common';
import { omit as LodashOmit } from 'lodash-es';
import { type EnrollmentDocument, EnrollmentModel } from '@/models/index.js';
import { batchInsertItems } from '../utils/batch-insert.js';

const processEnrollments = async (enrollment: EnrollmentDocument) => {
  const key = {
    ra: enrollment.ra,
    year: enrollment.year,
    quad: enrollment.quad,
    disciplina: enrollment.disciplina,
  };

  //The identifier is already generated by the caller of this function (syncEnrollments)
  //TODO: choose if I should generate the identifier here or in the caller
  const identifier = enrollment.identifier || generateIdentifier(key as any);
  const enrollmentsToUpdate = LodashOmit(enrollment, [
    'identifier',
    'id',
    '_id',
  ]);
  try {
    await EnrollmentModel.findOneAndUpdate(
      {
        identifier,
      },
      enrollmentsToUpdate,
      {
        new: true,
        upsert: true,
      },
    );
  } catch (error) {
    logger.error({ error }, 'Error updating enrollment');
  }
};

export function updateEnrollments(data: EnrollmentDocument[]) {
  try {
    return batchInsertItems(data, processEnrollments);
  } catch (error) {
    logger.error({ error }, 'Error updating enrollments');
    throw error;
  }
}
