export const TRACING_DIRECTION = {
  INCOMING: 'incoming',
  OUTGOING: 'outgoing',
} as const;

export const TRACING_MESSAGES = {
  INCOMING_REQUEST: 'INCOMING REQUEST',
  OUTGOING_REQUEST: 'OUTGOING REQUEST',
  INCOMING_RESPONSE: 'INCOMING RESPONSE',
  OUTGOING_RESPONSE: 'OUTGOING RESPONSE',
  OUTGOING_RESPONSE_WITH_5XX_STATUS: 'OUTGOING RESPONSE WITH 5XX STATUS',
  OUTGOING_RESPONSE_WITH_4XX_STATUS: 'OUTGOING RESPONSE WITH 4XX STATUS',
  INCOMING_REQUEST_FAILED: 'INCOMING REQUEST FAILED',
  OUTGOING_REQUEST_FAILED: 'OUTGOING REQUEST FAILED',
  INCOMING_RESPONSE_WITH_5XX_STATUS: 'INCOMING RESPONSE WITH 5XX STATUS',
  INCOMING_RESPONSE_WITH_4XX_STATUS: 'INCOMING RESPONSE WITH 4XX STATUS',
} as const;

export const JOB_NAMES = {
  COMPONENTS_ARCHIVES_PROCESSING: 'components_archives_processing',
  COMPONENTS_ARCHIVES_PROCESSING_SUMMARY:
    'components_archives_processing_summary',
  COMPONENTS_ARCHIVES_PROCESSING_PDF: 'components_archives_processing_pdf',
  ENROLLED_STUDENTS: 'enrolled_students',
  PROCESS_ENROLLED_STUDENTS: 'process_enrolled_students',
  CREATE_COMPONENT: 'create_component',
  HISTORY_PROCESSING: 'history_processing',
  HISTORY_PROCESSING_RETRY: 'history_processing_retry',
  USER_ENROLLMENTS_UPDATE: 'user_enrollments_update',
  PROCESS_COMPONENTS_ENROLLMENTS: 'process_components_enrollments',
  UFABC_PARSER_WEBHOOK_PROCESSING: 'ufabc_parser_webhook_processing',
} as const;

export const REQUESTERS = ['ufabc-next', 'ufabc-cronos'] as const;

export const HTTP_REDIS_KEY_PREFIX = 'http';
export const MAX_LOG_SIZE = 600 * 1024;

export const PARSER_WEBHOOK_EVENTS = {
  STUDENT_SYNCED: 'student.synced',
  STUDENT_FAILED: 'student.failed',
} as const;

export const PARSER_WEBHOOK_SUPPORTED_EVENTS = [
  PARSER_WEBHOOK_EVENTS.STUDENT_SYNCED,
  PARSER_WEBHOOK_EVENTS.STUDENT_FAILED,
] as const;
