export const TRACING_DIRECTION = {
  INCOMING: 'incoming',
  OUTGOING: 'outgoing',
} as const;

export const TRACING_MESSAGES = {
  INCOMING_REQUEST: 'INCOMING REQUEST',
  OUTGOING_RESPONSE: 'OUTGOING RESPONSE',
  OUTGOING_RESPONSE_WITH_5XX_STATUS: 'OUTGOING RESPONSE WITH 5XX STATUS',
  OUTGOING_RESPONSE_WITH_4XX_STATUS: 'OUTGOING RESPONSE WITH 4XX STATUS',
  INCOMING_REQUEST_FAILED: 'INCOMING REQUEST FAILED',
  OUTGOING_REQUEST_FAILED: 'OUTGOING REQUEST FAILED',
  INCOMING_RESPONSE_WITH_5XX_STATUS: 'INCOMING RESPONSE WITH 5XX STATUS',
  INCOMING_RESPONSE_WITH_4XX_STATUS: 'INCOMING RESPONSE WITH 4XX STATUS',
} as const;
