export function getMockedGroups(season: string) {
  return [
    {
      season,
      groupURL: 'https://chat.whatsapp.com/example1',
      codigo: 'BCJ0205-15',
      campus: 'sa' as const,
      turma: 'B1',
      turno: 'noturno',
      subject: 'Fenômenos Térmicos',
      teoria: 'Eduardo De Moraes Gregores',
      pratica: 'Marcos De Abreu Avila',
      uf_cod_turma: 'BCJ0205-15',
    },
    {
      season,
      groupURL: 'https://chat.whatsapp.com/example2',
      codigo: 'BCM0506-15',
      campus: 'sa' as const,
      turma: 'A2',
      turno: 'matutino',
      subject: 'Comunicação e Redes',
      teoria: 'Maria Silva Santos',
      pratica: 'João Pedro Oliveira',
      uf_cod_turma: 'BCM0506-15',
    },
    {
      season,
      groupURL: 'https://chat.whatsapp.com/example3',
      codigo: 'BCN0404-15',
      campus: 'sa' as const,
      turma: 'C1',
      turno: 'matutino',
      subject: 'Geometria Analítica',
      teoria: 'Ana Carolina Lima',
      pratica: 'Roberto Carlos Souza',
      uf_cod_turma: 'BCN0404-15',
    },
    {
      season,
      groupURL: 'https://chat.whatsapp.com/example4',
      codigo: 'BCS0001-15',
      campus: 'sbc' as const,
      turma: 'B3',
      turno: 'noturno',
      subject: 'Base Experimental das Ciências Naturais',
      teoria: 'Pedro Henrique Costa',
      pratica: 'Fernanda Rodrigues',
      uf_cod_turma: 'BCS0001-15',
    },
  ];
}
