name: Deploy Frontend

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/web/**'
      - 'apps/static/**'
      - 'packages/services/**'
      - 'packages/utils/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    env:
      MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
      VITE_MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
      VITE_AXIOM_TOKEN: ${{ secrets.WEB_AXIOM_INGEST_TOKEN }}
      VITE_AXIOM_DATASET: ${{ secrets.WEB_AXIOM_DATASET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_S3_BUCKET_NAME: ${{ github.ref == 'refs/heads/main' && secrets.AWS_S3_BUCKET_NAME_PRD  || secrets.AWS_S3_BUCKET_NAME_HOM }}
      AWS_DISTRIBUTION_ID: ${{ github.ref == 'refs/heads/main' && secrets.AWS_DISTRIBUTION_ID_PRD  || secrets.AWS_DISTRIBUTION_ID_HOM }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: shinyinc/action-aws-cli@v1.2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web
        run: pnpm turbo run build --filter=@next/web

      - name: Sync static with S3
        run: aws s3 sync apps/static s3://$AWS_S3_BUCKET_NAME --exclude '.gitkeep'

      - name: Sync web with S3
        run: aws s3 sync apps/web/dist s3://$AWS_S3_BUCKET_NAME/app

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id $AWS_DISTRIBUTION_ID --paths "/*"
